### ISSUE TITLE
.net 4.0

### ISSUE THREAD

**Issue by jenokizm** [WildGums/Orc.FileAssociation#2]
Hi, please 
1. add support .net 4.0 many programs still require compatibility with WinXp
2. add the ability to install the icon from the hard disk file

**Comment by GeertvanHorrik** [comment]
Thanks for reporting this ticket. We won't be adding .NET 4.0 support for the following reasons:

1. We removed it before releasing the 2.x release for Catel and all Orc packages (around 60). We won't be adding this back.
2. The reason we removed it is because both windows XP and .NET 4.0 are no longer supported by Microsoft. The primary customers of these packages are we (the creators). We provide the components for free though for everyone to use, but we won't be doing free / unpaid maintenance stuff we don't need ourselves.

The 2nd feature request is a good one, happy to accept a PR for that one. But we need to be realistic, .NET 4.0 support won't come to this library.

If this is something you can't overcome, you are always free to fork / create your own copy of this library and add .NET 4.0 support.
